-- # --- Sample dataset

# --- !Ups

insert into [dbo].[Location] ([Name]) values ('USA');

insert into [dbo].[Company] ([Name], [LocId]) values ('Apple Inc.', 1);
insert into [dbo].[Company] ([Name], [LocId]) values ('Thinking Machines', null);
insert into [dbo].[Company] ([Name], [LocId]) values ('RCA', null);
insert into [dbo].[Company] ([Name], [LocId]) values ('Netronics', null);
insert into [dbo].[Company] ([Name], [LocId]) values ('Tandy Corporation', null);
insert into [dbo].[Company] ([Name], [LocId]) values ('Commodore International', null);
insert into [dbo].[Company] ([Name], [LocId]) values ('MOS Technology', null);
insert into [dbo].[Company] ([Name], [LocId]) values ('Micro Instrumentation and Telemetry Systems', null);
insert into [dbo].[Company] ([Name], [LocId]) values ('IMS Associates, Inc.', null);
insert into [dbo].[Company] ([Name], [LocId]) values ('Digital Equipment Corporation', null);
insert into [dbo].[Company] ([Name], [LocId]) values ('Lincoln Laboratory', 1);
insert into [dbo].[Company] ([Name], [LocId]) values ('Moore School of Electrical Engineering', null);
insert into [dbo].[Company] ([Name], [LocId]) values ('IBM', null);
insert into [dbo].[Company] ([Name], [LocId]) values ('Amiga Corporation', null);
insert into [dbo].[Company] ([Name], [LocId]) values ('Canon', null);
insert into [dbo].[Company] ([Name], [LocId]) values ('Nokia', null);
insert into [dbo].[Company] ([Name], [LocId]) values ('Sony', null);
insert into [dbo].[Company] ([Name], [LocId]) values ('OQO', null);
insert into [dbo].[Company] ([Name], [LocId]) values ('NeXT', null);
insert into [dbo].[Company] ([Name], [LocId]) values ('Atari', null);
insert into [dbo].[Company] ([Name], [LocId]) values ('Acorn computer', null);
insert into [dbo].[Company] ([Name], [LocId]) values ('Timex Sinclair', null);
insert into [dbo].[Company] ([Name], [LocId]) values ('Nintendo', null);
insert into [dbo].[Company] ([Name], [LocId]) values ('Sinclair Research Ltd', null);
insert into [dbo].[Company] ([Name], [LocId]) values ('Xerox', null);
insert into [dbo].[Company] ([Name], [LocId]) values ('Hewlett-Packard', null);
insert into [dbo].[Company] ([Name], [LocId]) values ('Zemmix', null);
insert into [dbo].[Company] ([Name], [LocId]) values ('ACVS', null);
insert into [dbo].[Company] ([Name], [LocId]) values ('Sanyo', null);
insert into [dbo].[Company] ([Name], [LocId]) values ('Cray', null);
insert into [dbo].[Company] ([Name], [LocId]) values ('Evans & Sutherland', null);
insert into [dbo].[Company] ([Name], [LocId]) values ('E.S.R. Inc.', null);
insert into [dbo].[Company] ([Name], [LocId]) values ('OMRON', null);
insert into [dbo].[Company] ([Name], [LocId]) values ('BBN Technologies', null);
insert into [dbo].[Company] ([Name], [LocId]) values ('Lenovo Group', null);
insert into [dbo].[Company] ([Name], [LocId]) values ('ASUS', null);
insert into [dbo].[Company] ([Name], [LocId]) values ('Amstrad', null);
insert into [dbo].[Company] ([Name], [LocId]) values ('Sun Microsystems', null);
insert into [dbo].[Company] ([Name], [LocId]) values ('Texas Instruments', 1);
insert into [dbo].[Company] ([Name], [LocId]) values ('HTC Corporation', null);
insert into [dbo].[Company] ([Name], [LocId]) values ('Research In Motion', null);
insert into [dbo].[Company] ([Name], [LocId]) values ('Samsung Electronics', null);

insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('MacBook Pro 15.4 inch',null,null,1);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('CM-2a',null,null,2);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('CM-200',null,null,2);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('CM-5e',null,null,2);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('CM-5','1991-01-01',null,2);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('MacBook Pro','2006-01-10',null,1);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Apple IIe',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Apple IIc',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Apple IIGS',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Apple IIc Plus',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Apple II Plus',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Apple III','1980-05-01','1984-04-01',1);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Apple Lisa',null,null,1);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('CM-2',null,null,2);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Connection Machine','1987-01-01',null,2);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Apple II','1977-04-01','1993-10-01',1);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Apple III Plus','1983-12-01','1984-04-01',1);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('COSMAC ELF',null,null,3);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('COSMAC VIP','1977-01-01',null,3);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('ELF II','1977-01-01',null,4);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Macintosh','1984-01-24',null,1);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Macintosh II',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Macintosh Plus','1986-01-16','1990-10-15',1);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Macintosh IIfx',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('iMac','1998-01-01',null,1);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Mac Mini','2005-01-22',null,1);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Mac Pro','2006-08-07',null,1);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Power Macintosh','1994-03-01','2006-08-01',1);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('PowerBook','1991-01-01','2006-01-01',1);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Xserve',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Powerbook 100',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Powerbook 140',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Powerbook 170',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('PowerBook Duo',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('PowerBook 190',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Macintosh Quadra','1991-01-01',null,1);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Macintosh Quadra 900',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Macintosh Quadra 700',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Macintosh LC','1990-01-01',null,1);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Macintosh LC II','1990-01-01',null,1);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Macintosh LC III','1993-01-01',null,1);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Macintosh LC III+',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Macintosh Quadra 605','1993-10-21',null,1);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Macintosh LC 500 series',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('TRS-80 Color Computer','1980-01-01',null,5);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Acorn System 2',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Dragon 32/64',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('MEK6800D2',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Newbear 77/68',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Commodore PET',null,null,6);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Commodore 64','1982-08-01','1994-01-01',6);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Commodore 64C',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Commodore SX-64',null,null,6);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Commodore 128',null,null,6);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Apple I','1976-04-01','1977-10-01',1);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('KIM-1','1975-01-01',null,7);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Altair 8800','1974-12-19',null,8);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('IMSAI 8080','1975-08-01',null,9);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('IMSAI Series Two',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('VAX','1977-10-25',null,10);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('VAX 11/780','1977-10-25',null,10);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('VAX 11/750','1980-10-01',null,10);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('TX-2','1958-01-01',null,11);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('TX-0','1956-01-01',null,11);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Whirlwind','1951-04-20',null,11);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('ENIAC','1946-02-15','1955-10-02',12);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('IBM PC','1981-08-12',null,13);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Macintosh Classic',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Macintosh Classic II','1991-01-01',null,1);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Amiga','1985-01-01',null,14);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Amiga 1000',null,null,6);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Amiga 500','1987-01-01',null,6);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Amiga 500+',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Amiga 2000','1986-01-01','1990-01-01',6);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Amiga 3000',null,null,6);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Amiga 600','1992-03-01',null,6);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Macintosh 128K','1984-01-01',null,1);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Macintosh 512K','1984-09-10','1986-04-14',1);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Macintosh SE','1987-03-02','1989-08-01',1);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Macintosh SE/30','1989-01-19','1991-10-21',1);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Canon Cat','1987-01-01',null,15);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Nokia 770',null,null,16);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Nokia N800','2007-01-01',null,16);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Mylo','2006-09-21',null,17);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('OQO 02','2007-01-01',null,18);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('OQO 01+',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Pinwheel calculator',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('iBook',null,null,1);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('MacBook','2006-05-16',null,1);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('NeXTstation','1990-01-01','1993-01-01',19);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('NeXTcube','1988-01-01','1993-01-01',19);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('NeXTstation Color Turbo',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('NeXTstation Color',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('NeXTstation Turbo',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('NeXTcube Turbo',null,null,19);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('NeXTcube 040',null,null,19);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('NeXTcube 030',null,null,19);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Tinkertoy Tic-Tac-Toe Computer',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Z3',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Z4',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Z1',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Z2',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Wang 2200','1973-05-01',null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Wang VS',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Wang OIS',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('BBC Micro',null,null,21);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('IBM 650','1953-01-01','1962-01-01',13);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Cray-1',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Cray-3',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Cray-2',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Cray-4',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Cray X1',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Cray XD1',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Cray T3D','1993-01-01',null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Cray T3E','1995-01-01',null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Cray C90',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Cray T90',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Cray SV1',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Cray J90',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Cray XT3',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Cray CS6400',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Atari ST','1985-01-01','1993-01-01',20);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Amiga 2500',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Amiga 2500',null,null,6);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Amiga 4000',null,null,6);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Amiga 3000UX',null,null,6);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Amiga 3000T',null,null,6);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Amiga 4000T',null,null,6);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Amiga 1200','1992-10-01','1996-01-01',6);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Atari 1040 STf','1986-01-01',null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Atari 520 ST','1985-01-01',null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Atari 520 STfm','1986-01-01',null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Atari 1040 STe','1989-01-01',null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Atari MEGA STe','1991-01-01',null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Atari 520 ST+','1985-01-01',null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Atari 520 STm','1985-01-01',null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Atari 130 ST','1985-01-01',null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Atari 260 ST','1985-01-01',null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Atari MEGA ST','1987-01-01',null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Atari 520 STf','1986-01-01',null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Atari 1040 STfm','1986-01-01',null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Atari 2080 ST','1986-01-01',null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Atari 260 ST+','1985-01-01',null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Atari 4160 STe','1988-01-01',null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('TRS-80 Color Computer 2',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('TRS-80 Color Computer 3',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('TRS-80 Model 1','1977-01-01',null,5);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Timex Sinclair 2068','1983-11-01','1984-04-01',22);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('ZX Spectrum','1982-01-01',null,24);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Xerox Star','1981-01-01',null,25);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Xerox Alto',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Acorn Archimedes',null,null,21);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Nintendo Entertainment System',null,null,23);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Super Nintendo Entertainment System','1991-08-01','1999-01-01',23);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Super Famicom',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Nintendo GameCube',null,null,23);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Game Boy line',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('PlayStation','1994-12-03',null,17);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('PlayStation 2','2000-03-24',null,17);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Game & Watch',null,null,23);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('EDSAC',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('IBM System/4 Pi',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('IBM AP-101',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('IBM TC-1',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('IBM AP-101B',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('IBM AP-101S',null,null,13);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('ProLiant',null,null,26);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Http://nepomuk.semanticdesktop.org/xwiki/',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Sinclair QL','1984-01-01','1986-01-01',24);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Sinclair ZX81','1981-01-01',null,24);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Sinclair ZX80',null,null,24);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Atari 65XE',null,null,20);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Deep Blue',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Macintosh Quadra 650',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Macintosh Quadra 610',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Macintosh Quadra 800',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Macintosh Quadra 950',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('PowerBook 160',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('PowerBook 145B',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('PowerBook 170',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('PowerBook 145',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('PowerBook G3',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('PowerBook 140',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Macintosh IIcx',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Powerbook 180',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('PowerBook G4',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Macintosh XL',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('PowerBook 100',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('PowerBook 2400c',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('PowerBook 1400',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Macintosh Quadra 630',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Macintosh Quadra 660AV',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Macintosh Quadra 840AV',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('PowerBook 5300',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('PowerBook 3400c',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Macintosh Color Classic',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Macintosh 512Ke',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Macintosh IIsi',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Macintosh IIx',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('PowerBook 500 series',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Power Macintosh G3',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Macintosh IIci',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('iMac G5','2004-08-31',null,1);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Power Mac G4',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Power Macintosh 7100',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Power Macintosh 9600',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Power Macintosh 7200',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Power Macintosh 7300',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Power Macintosh 8600',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Power Macintosh 6200',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Power Macintosh 8100',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Compact Macintosh',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Power Macintosh 4400',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Power Macintosh 9500',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Macintosh Portable',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('EMac',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Power Macintosh 7600',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Power Mac G5',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Power Macintosh 7500',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Power Macintosh 6100',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Power Macintosh 8500',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Macintosh IIvi',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Macintosh IIvx',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('IMac G3',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('IMac G4',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Power Mac G4 Cube',null,null,1);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Intel iMac',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Deep Thought',null,null,13);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Wii','2006-11-19',null,23);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('IBM System x',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('IBM System i','2006-01-01',null,13);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('IBM System z','2006-01-01',null,13);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('IBM System p','2000-01-01',null,13);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('LC 575',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Macintosh TV',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Macintosh Performa',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Macintosh II series',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Power Macintosh 6400',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Power Macintosh 6500',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Apple PenLite',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Wallstreet',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Twentieth Anniversary Macintosh',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Power Macintosh 5500',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('iBook G3',null,null,1);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Power Macintosh 5200 LC',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Power Macintosh 5400',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('CM-1',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('MSX','1983-01-01','1995-01-01',27);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('PlayStation 3',null,null,17);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('MSX2','1986-01-01',null,28);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('MSX2+','1988-01-01',null,29);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('MSX turbo R','1990-01-01',null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Panasonic FS A1GT',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Panasonic FS A1ST',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('PDP-11',null,null,10);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('PDP-1',null,null,10);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('PDP-10',null,null,10);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('PDP-8',null,null,10);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('PDP-6',null,null,10);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('DECSYSTEM-20',null,null,10);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('PDP-7',null,null,10);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('PDP-5',null,null,10);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('PDP-12',null,null,10);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('LINC',null,null,10);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('PDP-14',null,null,10);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('PDP-15',null,null,10);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('PDP-16',null,null,10);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Cray X2','2007-01-01',null,30);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Cray X-MP','1982-01-01',null,30);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Evans & Sutherland ES-1',null,null,31);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Commodore VIC-20','1980-01-01',null,6);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('PowerBook 150',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('MacBook Air','2008-01-15',null,1);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Digi-Comp I','1963-01-01',null,32);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Digi-Comp',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Digi-Comp II',null,null,32);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Manchester Mark I','1949-01-01',null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Small-Scale Experimental Machine','1948-01-01',null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Nintendo 64',null,null,23);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Game Boy Advance',null,null,23);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Game Boy',null,null,23);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Nintendo DS Lite',null,null,23);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Nintendo DS','2004-01-01',null,23);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Game Boy Color',null,null,23);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Game Boy Advance SP',null,null,23);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Virtual Boy',null,null,23);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Game Boy Micro',null,null,23);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Roadrunner',null,null,13);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('HP 9000',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('OMRON Luna-88K2',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('OMRON Luna-88K',null,null,33);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Motorola series 900',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Motorola M8120',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Triton Dolphin System 100',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('BBN TC2000','1989-08-01',null,34);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('WRT54G',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('ThinkPad','1992-01-01',null,35);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Apple Newton','1993-01-01','1998-01-01',1);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Atanasoff-Berry Computer','1937-01-01',null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Atlas Computer','1962-01-01','1974-01-01',null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('ASUS Eee PC 901',null,null,36);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('ASUS Eee PC 701',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('IBM 7030','1961-01-01',null,13);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('System/38','1979-01-01',null,13);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('System/36','1983-01-01','2000-01-01',13);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('IBM 7090','1959-01-01',null,13);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('IBM RT',null,null,13);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('System/360','1964-01-01',null,13);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('IBM 801','1980-01-01',null,13);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('IBM 1401','1959-01-01',null,13);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('ASCI White','2001-01-01','2006-01-01',13);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Blue Gene',null,null,13);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('ASCI Blue Pacific','1998-01-01',null,13);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('iPhone','2007-06-01',null,1);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Nokia N810','2007-10-17',null,16);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('EDSAC 2',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Titan',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Pilot ACE',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('HP Mini 1000','2008-10-29',null,26);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('HP 2133 Mini-Note PC','2008-04-15',null,26);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Kogan Agora Pro','2008-12-04',null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('D-Series Machines',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('ZX Spectrum 48K','1982-01-01',null,24);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('ZX Spectrum 16K','1982-01-01',null,24);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('ZX Spectrum 128','1985-09-01',null,24);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('ZX Spectrum +3',null,null,37);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('ZX Spectrum +2','1986-01-01',null,37);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('ZX Spectrum +2A','1987-01-01',null,37);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('ZX Spectrum +','1984-06-01',null,24);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Acer Extensa',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Acer Extensa 5220',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Dell Latitude',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Toshiba Satellite',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Timex Sinclair 2048',null,null,22);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Sprinter',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Timex Computer 2048',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Pentagon',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Belle',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Loki',null,null,24);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Hobbit',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('NeXT Computer',null,null,19);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('TRS-80',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('TRS-80 Model 2','1980-01-01',null,5);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('TRS-80 Model 3',null,null,5);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('STacy','1989-01-01',null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('ST BOOK','1990-01-01',null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Atari 520 STE','1989-01-01',null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Amiga 2000 Model A',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Amiga 2000 Model B',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Amiga 2000 Model C',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('IBM 3270',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('CALDIC',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Modbook',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Compaq SystemPro',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('ARRA',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('IBM System Cluster 1350',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Finite element machine',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('ES7000',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('HP MediaSmart Server',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('HP Superdome',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('IBM Power Systems','2008-01-01',null,13);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Oslo Analyzer',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Microsoft Softcard',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('WITCH',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Analytical engine',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('EDVAC',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('BINAC',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Earth Simulator',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('BARK',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Harvard Mark I','1944-01-01',null,13);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('ILLIAC IV',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('ILLIAC II',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('ILLIAC III',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Water integrator',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('CSIRAC',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('System X',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Harvest',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('ChipTest',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('HiTech',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Bomba',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('ACE',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('ASCI Red',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('ASCI Thors Hammer',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('ASCI Purple','2005-01-01',null,13);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('ASCI Blue Mountain',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Columbia',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('HP Integrity',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('APEXC',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Datasaab D2',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('BRLESC',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('DYSEAC',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('SSEC','1948-01-01',null,13);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Hydra',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('FUJIC',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('RAYDAC',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Harvard Mark III',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('DATAR',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('ReserVec',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('DASK',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('UTEC',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('DRTE Computer',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('PowerEdge',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Apple Network Server',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Goodyear MPP',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Macintosh 128K technical details',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Power Macintosh G3',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('CER-10',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('CER-20',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('IBM BladeCenter','2002-01-01',null,13);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Wisconsin Integrally Synchronized Computer',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Amstrad CPC',null,null,37);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Amstrad CPC 6128',null,null,37);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Amstrad CPC 664',null,null,37);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Amstrad CPC 464',null,null,37);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Intergraph',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Enterprise',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('MTX500',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Acorn Electron',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Sony Vaio P','2009-02-01',null,17);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('VAIO',null,null,17);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Sony Vaio P VGN-P588E/Q',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Sony Vaio P VGN-P530H/G',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Sony Vaio P VGN-P530H/W',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Sony Vaio P VGN-P530H/Q',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Sony Vaio P VGN-P530H/R',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Sony Vaio P VGN-P588E/R',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Sony Vaio P VGN-P598E/Q',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Timex Sinclair 1000','1982-07-01',null,22);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Komputer 2086',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Galaksija',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Vector-06C',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Elektronika BK',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Sun386i',null,null,38);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Xerox Daybreak','1985-01-01','1989-01-01',null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Xerox NoteTaker',null,null,25);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('D4a','1965-01-01',null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('LGP-30',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('LGP-21',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('ASUS Eee PC 900','2008-05-01',null,36);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Atari TT030',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Bi Am ZX-Spectrum 48/64',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Bi Am ZX-Spectrum 128',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('PlayStation Portable',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('MSI Wind Netbook',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Sharp Mebius NJ70A','2009-04-21',null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('HTC Snap',null,null,40);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Commodore Educator 64',null,null,6);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Amiga 1500',null,null,6);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Commodore 65',null,null,6);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Commodore 16',null,null,6);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Commodore CBM-II',null,null,6);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Commodore Plus/4',null,null,6);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Commodore LCD',null,null,6);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Commodore MAX Machine',null,null,6);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Aster CT-80',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Test','2009-01-01','2009-01-01',null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('MSI GX723',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Eee PC 1000HV','2009-05-22',null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('VTech Laser 200','1983-01-01',null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('CrunchPad',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Neo Geo','1990-01-01',null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Sega Mega Drive',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Sega Master System',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('TurboGrafx-16',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Sun-3',null,null,38);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Pleiades',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('IBM Sequoia',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Inves Spectrum 48k plus',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('iPhone 3G',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('iPhone 3GS',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Beagle Board',null,null,39);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('HP nPar',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('MacBook Family',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Reservisor',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('BladeSystem',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('lenovo thinkpad t60p',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('lenovo thinkpad x200',null,null,35);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('lenovo thinkpad t60',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('lenovo thinkpad w700',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('lenovo thinkpad t41',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('lenovo thinkpad z61p',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('lenovo thinkpad x61s',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('lenovo thinkpad t43',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('lenovo thinkpad r400',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('lenovo thinkpad x60s',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('lenovo thinkpad x301',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('lenovo thinkpad t42',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('lenovo thinkpad r61',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('lenovo thinkpad w500',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('lenovo thinkpad sl400',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('lenovo thinkpad x40',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('lenovo thinkpad x200 tablet',null,null,35);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('lenovo thinkpad t400s',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Nokia N900','2009-10-01',null,16);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Internet Tablet',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Meiko Computing Surface','1986-01-01','1993-01-01',null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('CS-2',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('IBM 701','1952-01-01',null,13);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('IBM 5100','1975-01-01',null,13);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('AN/FSQ-7','1958-01-01',null,13);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('AN/FSQ-32','1960-01-01',null,13);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('IBM CPC','1949-01-01',null,13);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('System/34','1978-01-01','1983-01-01',13);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('System/32','1975-01-01',null,13);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('System/3','1969-01-01','1985-01-01',13);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('IBM 305','1956-01-01',null,13);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('English Electric DEUCE',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('CER-203',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('CER-22',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Kentucky Linux Athlon Testbed',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('QNAP TS-101',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('iPad','2010-01-01','2011-03-02',1);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('iPhone 2G',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Inslaw',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('WePad','2010-07-01',null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('MacBook Parts',null,null,1);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('MacBook 13-inch Core 2 Duo 2.13GHz (MC240LL/A) DDR2 Model',null,null,1);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('MacBook 13-inch Core 2 Duo 2.13GHz (MC240T/A) DDR2 Model',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('MacBook 13-inch Core 2 Duo 2.13GHz (MC240X/A) DDR2 Model',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('MacBook 13-inch Core 2 Duo 2.26GHz (Unibody MC207LL/A) DDR3 Model',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('MC240LL/A',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('D.K.COMMUNICATION',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('iPhone 4',null,null,1);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Nintendo 3DS','2010-03-23',null,23);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('ASUS Eee PC 1005PE','2010-01-01',null,36);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('National Law Enforcement System',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('BlackBerry PlayBook',null,null,41);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Barnes & Noble nook','2009-10-20',null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('SAM Coupé',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('HTC Dream','2008-10-22',null,40);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Samsung Galaxy Tab','2010-09-02',null,42);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('BlackBerry PlayBook','2010-09-27',null,41);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Tianhe-I',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Kno',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('ThinkPad 701 C',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('ThinkPad 340 CSE',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('ThinkPad 755 CX',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('ThinkPad 755 CE',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('ThinkPad 370 C',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Coleco Adam','1983-01-01',null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Nebulae',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Alex eReader',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Acer Iconia',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Archos 101',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Fujitsu Lifebook T900',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Motorola Xoom',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('ViewSonic G Tablet',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('DEC Professional','1982-01-01',null,10);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('DEC Multia','1994-11-07',null,10);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('DEC Firefly',null,null,10);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('DEC 3000 AXP',null,null,10);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('DEC 2000 AXP','1993-05-25',null,10);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('DEC 4000 AXP','1992-11-10',null,10);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('DEC 7000/10000 AXP','1992-11-10',null,10);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('DEC Professional 350',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('DEC Rainbow 100',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('DEC Professional 325',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('DECmate II',null,null,10);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('DECmate',null,null,10);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('DECsystem',null,null,10);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('NetApp Filer',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('DEC GT40',null,null,10);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('ecoATM',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('MindWave BrainCubed Education Bundle',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('PalmPilot',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Upcoming iPhone 5',null,null,1);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Dell Inspiron 560 Desktop Computer ',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('IPad 2',null,null,1);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('HP TouchPad','2011-02-09',null,26);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('HP Veer','2011-02-09',null,26);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Lenovo Thinkpad Edge 11',null,null,35);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Dell Vostro',null,null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('Gateway LT3103U','2008-01-01',null,null);
insert into [dbo].[Computer] ([Name],[Introduced],[Discontinued],[CompanyId]) values ('iPhone 4S','2011-10-14',null,1);

# --- !Downs

delete from [dbo].[Computer];
delete from [dbo].[Company];
